#pragma once
#include "common.h"

class CodegenInfo;

TokenValue success(CodegenInfo*,vector<TokenValue>);
TokenValue program_empty_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue program_addfundef_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue program_addvardefreduce(CodegenInfo*,vector<TokenValue>);
TokenValue intvalexpr_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue boovalexpr_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue stringvalexpr_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue operator_n_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue function_norettype_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue function_withrettype_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue parameter_list_empty_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue parameter_list_parameter_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue parameter_list_addparameter_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue parameter_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue variabledef_list_variabledef_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue variabledef_list_addvariabledef_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue variabledef_nonassignment_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue variabledef_withassignment_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue statement_list_empty_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue statement_list_addstatement(CodegenInfo*,vector<TokenValue>);
TokenValue statement_expression_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue statement_list_variabledef_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue expression_primary_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue expression_add_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue expression_addparen_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue funcallexpr_variable_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue funcallexpr_closure_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue variableexpr_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue parenexpr_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue returnstatement_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue returnstatement_noexp_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue type_normal_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue type_fun_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue type_list_empty_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue type_list_type_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue type_list_addtype_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue closureexpr_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue arg_list_empty_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue arg_list_expression_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue arg_list_addexpression_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue ifstatement_noelse_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue ifstatement_withelse_reduce(CodegenInfo*,vector<TokenValue>);
TokenValue block_reduce(CodegenInfo *cgi,vector<TokenValue> values);
TokenValue while_reduce(CodegenInfo *cgi,vector<TokenValue> values);
